[server]
host = "0.0.0.0"
port = 19881

[files]
pid_file = "/tmp/vhttpd_hello.pid"
event_log = "/tmp/vhttpd_hello.events.ndjson"

[worker]
autostart = true
read_timeout_ms = 3000
socket = "/tmp/vslim_hello.sock"
cmd = "php -d extension=/app/vslim/vslim.so /app/vslim/httpd/php-worker.php"

[worker.env]
VSLIM_HTTPD_APP = "/app/vslim/examples/hello-app.php"

[admin]
host = "0.0.0.0"
port = 19981
token = ""
