[server]
host = "127.0.0.1"
port = 19881

[files]
pid_file = "/tmp/vhttpd.pid"
event_log = "/tmp/vhttpd.events.ndjson"

[worker]
read_timeout_ms = 3000
autostart = true
pool_size = 4
socket_prefix = "/tmp/vslim_worker"
max_requests = 5000
restart_backoff_ms = 500
restart_backoff_max_ms = 8000
cmd = "php -d extension=/Users/guweigang/Source/vphpext/vslim/vslim.so /Users/guweigang/Source/vphpext/vhttpd/php/php-worker.php --socket {socket}"

[worker.env]
VSLIM_HTTPD_APP = "/Users/guweigang/Source/vphpext/vhttpd/examples/hello-app.php"

[admin]
host = "127.0.0.1"
port = 19981
token = "change-me"
