[server]
host = "127.0.0.1"
port = 19882

[files]
pid_file = "/tmp/vhttpd_ai_stream.pid"
event_log = "/tmp/vhttpd_ai_stream.events.ndjson"

[worker]
autostart = true
read_timeout_ms = 3000
socket = "/tmp/vslim_ai_stream.sock"
cmd = "VSLIM_HTTPD_APP=/Users/guweigang/Source/vphpext/vslim/examples/ai-stream-app.php php -d extension=/Users/guweigang/Source/vphpext/vslim/vslim.so /Users/guweigang/Source/vphpext/vslim/httpd/php-worker.php --socket /tmp/vslim_ai_stream.sock"

[admin]
host = "127.0.0.1"
port = 19982
token = ""
