[server]
host = "127.0.0.1"
port = 19881

[files]
pid_file = "/tmp/vhttpd_hello.pid"
event_log = "/tmp/vhttpd_hello.events.ndjson"

[worker]
autostart = true
read_timeout_ms = 3000
socket = "/tmp/vslim_hello.sock"
cmd = "php -d extension=/Users/guweigang/Source/vphpext/vslim/vslim.so /Users/guweigang/Source/vphpext/vslim/httpd/php-worker.php"

[worker.env]
VSLIM_HTTPD_APP = "/Users/guweigang/Source/vphpext/vslim/examples/hello-app.php"

[admin]
host = "127.0.0.1"
port = 19981
token = ""
