[server]
host = "127.0.0.1"
port = 19887

[files]
pid_file = "/tmp/vhttpd_wordpress.pid"
event_log = "/tmp/vhttpd_wordpress.events.ndjson"

[worker]
autostart = true
read_timeout_ms = 3000
socket = "/tmp/vslim_wordpress.sock"
cmd = "VSLIM_HTTPD_APP=/Users/guweigang/Source/vphpext/vslim/examples/wordpress/app.php VSLIM_WP_ROOT=/ABS/PATH/TO/WORDPRESS php -d extension=/Users/guweigang/Source/vphpext/vslim/vslim.so /Users/guweigang/Source/vphpext/vslim/httpd/php-worker.php --socket /tmp/vslim_wordpress.sock"

[admin]
host = "127.0.0.1"
port = 19987
token = ""
